# Generated by Django 5.2.6 on 2025-09-20 21:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.UUIDField()),
                ('student_id', models.UUIDField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('late', 'Tardío'), ('excused', 'Justificado')], default='present', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'attendance',
                'ordering': ['-date'],
                'unique_together': {('course_id', 'student_id', 'date')},
            },
        ),
    ]
