# Generated by Django 5.2.6 on 2025-09-20 21:38

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author_id', models.UUIDField()),
                ('target_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, help_text='Roles que pueden ver este anuncio. Dejar vacío para todos los roles.', null=True, size=None)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
