// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvucxenjdfxxqtekhqfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2dWN4ZW5qZGZ4eHF0ZWtocWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjc5ODgsImV4cCI6MjA3MzcwMzk4OH0.2gEVpAzhfTVqpJi3FqXn-WK__Nf209dtDs0s73geu9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});